### PR TITLE
fix : move command exec into golang http in irgsh-cli.

### PR DESCRIPTION
**Pull request by ervinismu**
Replace `exec.Command` with golang `http` in `irgsh-cli update`, relate to this Issue ([#75](https://github.com/BlankOn/irgsh-go/issues/75))

### CODE REVIEW

**Comment by herpiko** [comment]
@ervinismu `python-apt` has been dropped since bullseye/jammy.

You may want to change `python-apt` to `python3-apt`

https://github.com/search?q=repo%3ABlankOn%2Firgsh-go%20python-apt&type=code

**Comment by ervinismu** [comment]
> @ervinismu `python-apt` has been dropped since bullseye/jammy.
> 
> You may want to change `python-apt` to `python3-apt`
> 
> https://github.com/search?q=repo%3ABlankOn%2Firgsh-go%20python-apt&type=code

thanks pak @herpiko ..
already replace it with `pyhton3-apt`. But , found error in `Create Release` step
```
Error: Resource not accessible by integration
```

**Comment by herpiko** [comment]
@ervinismu please pull from master as https://github.com/BlankOn/irgsh-go/pull/149 has been merged.

**Review by herpiko — APPROVED** [review]

**Comment by herpiko** [comment]
@ervinismu Thanks!

**Pull request merged**
